---
title: September Gallery
timezone: America/New_York
collections:
  posts:
    title: Posts
    output: true
  space:
    title: Space
    output: true
  uploads:
    title: Uploads
    output: true
  work:
    title: Work
    output: true
defaults:
- scope:
    path: ''
    type: work
  values:
    layout: artist
    title: Artist Name
    key_image: ''
    key_image_credit: ''
    is_always: false
    is_sometimes: false
    first_letter_of_last_name: ''
    exhibition_links:
      Link Title One: ''
    images:
    - ''
    images_with_captions:
    - image: ''
      caption: ''
    research_links:
      Link One: ''
    catalog_link:
      Catalog: ''
- scope:
    path: ''
    type: space
  values:
    layout: exhibition
    title: Exhibition Name
    key_image: ''
    key_image_credit: ''
    is_event: false
    start_date: ''
    end_date: ''
    opening_start_time_and_date: ''
    opening_end_time_and_date: ''
    artist_links:
      Artist Name One: ''
    images:
    - ''
    images_with_captions:
    - image: ''
      caption: ''
    research_links:
      Link One: ''
    catalog_link:
      Catalog: ''
gallery_hours: "Friday-Sunday, 12-5pm\nAppointments are not needed.\nFollowing the
  DCD guidelines, we no longer require masks for anyone who is vaccinated. However,
  we have masks available and are more than happy to accommodate any visitor by wearing
  one. "
is_closed: true
why_youre_closed: 
email: kristen@septembergallery.com
description: SEPTEMBER is a gallery, a room, a practice. We exhibit and support contemporary
  artists. We believe that being receptive to change is essential for the creative
  process. We provide a platform for exceptional individuals who have not been historically
  centered with care because of their inherited, chosen or perceived identity. We
  engage our local community while exhibiting artists from other cities and countries.
  We concentrate on visual artists, and collaborate with curators, performers, activists,
  poets, chefs, writers and other creatives. We opened in 2016 in Hudson, NY.
writing: SEPTEMBER is a gallery, a room, a practice. We exhibit and support contemporary
  artists. We believe that being receptive to change is essential for the creative
  process. We provide a platform for exceptional individuals who have not been historically
  centered with care because of their inherited, chosen or perceived identity. We
  engage our local community while exhibiting artists from other cities and countries.
  We concentrate on visual artists, and collaborate with curators, performers, activists,
  poets, chefs, writers and other creatives. We opened in 2016 in Hudson, NY.
physical_address: '449 Warren Street #3, Hudson, NY 12534'
url: http://septembergallery.com
facebook_username: septembergallery
instagram_username: septembergallery
baseurl: "/"
markdown: kramdown
plugins:
- jekyll-sitemap
- jekyll-seo-tag
