---
title: September Gallery
timezone: America/New_York
collections:
  posts:
    title: Posts
    output: true
  space:
    title: Space
    output: true
  uploads:
    title: Uploads
    output: true
  work:
    title: Work
    output: true
defaults:
- scope:
    path: ''
    type: work
  values:
    layout: artist
    title: Artist Name
    key_image: ''
    key_image_credit: ''
    is_always: false
    is_sometimes: false
    first_letter_of_last_name: ''
    exhibition_links:
      Link Title One: ''
    images:
    - ''
    research_links:
      Link One: ''
    catalog_link:
      Catalog: ''
- scope:
    path: ''
    type: space
  values:
    layout: exhibition
    title: Exhibition Name
    key_image: ''
    key_image_credit: ''
    is_event: false
    start_date: ''
    end_date: ''
    opening_start_time_and_date: ''
    opening_end_time_and_date: ''
    artist_links:
      Artist Name One: ''
    images:
    - ''
    research_links:
      Link One: ''
    catalog_link:
      Catalog: ''
gallery_hours: Friday-Sunday, noon-6pm and by appointment.
is_closed: 
why_youre_closed: 
email: kristen@septembergallery.com
description: |-
  SEPTEMBER is an evolving platform for artists of diverse disciplines. The gallery is committed to engaging the surrounding community, while hosting artists predominantly from Upstate to Brooklyn to Boston. In the first year and a half, over 200 artists have exhibited at the gallery. The spirited ethos and activity of SEPTEMBER includes performers, academics, activists, chefs, curators, writers, and other creative thinkers, makers and doers.

  SEPTEMBER was founded by Kristen Dodge in 2016 and is located in the Arcade Building at 449 Warren Street #3, Hudson, NY 12534.
writing: |
  SEPTEMBER is an evolving platform for artists of diverse disciplines. The gallery is committed to engaging the surrounding community, while hosting artists predominantly from Upstate to Brooklyn to Boston. In the first year and a half, over 200 artists have exhibited at the gallery. The spirited ethos and activity of SEPTEMBER includes performers, academics, activists, chefs, curators, writers, and other creative thinkers, makers and doers.

  SEPTEMBER was founded by Kristen Dodge in 2016 and is located in the Arcade Building at 449 Warren Street #3, Hudson, NY 12534.
physical_address: '449 Warren Street #3, Hudson, NY 12534'
url: http://septembergallery.com
facebook_username: septembergallery
instagram_username: septembergallery
baseurl: "/"
markdown: kramdown
gems:
- jekyll-sitemap
