---
title: September
timezone: America/New_York
collections:
  posts:
    title: Posts
    output: true
  space:
    title: Space
    output: true
  uploads:
    title: Uploads
    output: true
  work:
    title: Work
    output: true
defaults:
- scope:
    path: ''
    type: work
  values:
    layout: artist
    title: Artist Name
    key_image: ''
    is_artist_represented: false
    is_artist_exhibited: false
    exhibition_links:
      Link Title One: www.link.com
      Link Title Two: www.link.com
    images:
    - ''
    - ''
    - ''
    research_links:
      Link One: www.link.com
      Link Two: www.link.com
    catalog_link:
      Catalog: www.link.com
- scope:
    path: ''
    type: space
  values:
    layout: exhibition
    title: Exhibition Name
    key_image: ''
    is_event: false
    start_date: ''
    end_date: ''
    start_time: ''
    end_time: ''
    artist_links:
      Artist Name One: www.link.com
      Artist Namte Two: www.link.com
    images:
    - ''
    - ''
    - ''
    research_links:
      Link One: www.link.com
      Link Two: www.link.com
    catalog_link:
      Catalog: www.link.com
email: kristen@septembergallery.com
description: |
  September Gallery.
physical_address: 449 Warren Street Hudson, NY 12534
hours_of_operation: Friday through Monday 12 to Six
baseurl: 
url: http://septembergallery.com
facebook_username: septembergallery
instagram_username: septembergallery
markdown: kramdown
