---
title: September Gallery
timezone: America/New_York
collections:
  posts:
    title: Posts
    output: true
  space:
    title: Space
    output: true
  uploads:
    title: Uploads
    output: true
  work:
    title: Work
    output: true
defaults:
- scope:
    path: ''
    type: work
  values:
    layout: artist
    title: Artist Name
    key_image: ''
    key_image_credit: ''
    is_always: false
    is_sometimes: false
    first_letter_of_last_name: ''
    exhibition_links:
      Link Title One: ''
    images:
    - ''
    images_with_captions:
    - image: ''
      caption: ''
    research_links:
      Link One: ''
    catalog_link:
      Catalog: ''
- scope:
    path: ''
    type: space
  values:
    layout: exhibition
    title: Exhibition Name
    key_image: ''
    key_image_credit: ''
    is_event: false
    start_date: ''
    end_date: ''
    opening_start_time_and_date: ''
    opening_end_time_and_date: ''
    artist_links:
      Artist Name One: ''
    images:
    - ''
    images_with_captions:
    - image: ''
      caption: ''
    research_links:
      Link One: ''
    catalog_link:
      Catalog: ''
gallery_hours: Friday-Sunday, 12-5pm
is_closed: true
why_youre_closed: We are currently open by appointment only.
email: kristen@septembergallery.com
description: |-
  SEPTEMBER is an evolving platform for artists of diverse disciplines. The gallery is committed to prioritizing the work of women-identified and LGBTQIA+ artists. SEPTEMBER supports the surrounding community, and exhibits artists predominantly from Upstate New York, Brooklyn, and Boston. Along with visual artists, SEPTEMBER works with performers, activists, poets, chefs, dancers, writers, and other creatives for both exhibition and event programming. SEPTEMBER has worked with over 250 artists since opening four years ago.

  SEPTEMBER was founded by Kristen Dodge in 2016 and is located in the Arcade Building at 449 Warren Street #3, Hudson, NY 12534.
writing: |-
  SEPTEMBER is an evolving platform for artists of diverse disciplines. The gallery is committed to prioritizing the work of women-identified and LGBTQIA+ artists. SEPTEMBER supports the surrounding community, and exhibits artists predominantly from Upstate New York, Brooklyn, and Boston. Along with visual artists, SEPTEMBER works with performers, activists, poets, chefs, dancers, writers, and other creatives for both exhibition and event programming. SEPTEMBER has worked with over 250 artists since opening four years ago.

  SEPTEMBER was founded by Kristen Dodge in 2016 and is located in the Arcade Building at 449 Warren Street #3, Hudson, NY 12534.
physical_address: '449 Warren Street #3, Hudson, NY 12534'
url: http://septembergallery.com
facebook_username: septembergallery
instagram_username: septembergallery
baseurl: "/"
markdown: kramdown
gems:
- jekyll-sitemap
- jekyll-seo-tag
