---
title: September Gallery
timezone: America/New_York
collections:
  posts:
    title: Posts
    output: true
  space:
    title: Space
    output: true
  uploads:
    title: Uploads
    output: true
  work:
    title: Work
    output: true
defaults:
- scope:
    path: ''
    type: work
  values:
    layout: artist
    title: Artist Name
    key_image: ''
    is_always: false
    is_sometimes: false
    first_letter_of_last_name: ''
    exhibition_links:
      Link Title One: ''
    images:
    - ''
    research_links:
      Link One: ''
    catalog_link:
      Catalog: ''
- scope:
    path: ''
    type: space
  values:
    layout: exhibition
    title: Exhibition Name
    key_image: ''
    is_event: false
    start_date: ''
    end_date: ''
    opening_start_time_and_date: ''
    opening_end_time_and_date: ''
    artist_links:
      Artist Name One: ''
    images:
    - ''
    research_links:
      Link One: ''
    catalog_link:
      Catalog: ''
email: kristen@septembergallery.com
description: |
  September Gallery.
writing: 'SEPTEMBER was founded by Kristen Dodge in 2016. The space is located at
  449 Warren Street #3, Hudson, NY 12534. Our exhibition programming launched with
  Blue Jean Baby, featuring the work of 16 artists from Boston, Los Angeles, Brooklyn,
  Upstate New York, and Zurich. The opening event of SEPTEMBER was Psycho Daisies;
  the first installment of an on-going performance series called Arcade Bloc, named
  after the location of the gallery at The Arcade Building, and giving nod to the
  mission of creating common purpose. The programming will feature 6 exhibitions annually,
  an on-going performance series, and readings by selected writers. Curators will
  be invited to propose exhibitions and events. SEPTEMBER is a platform for Artists
  of diverse and committed disciplines. SEPTEMBER is named after a month that foreshadows
  a season of transition.'
physical_address: '449 Warren Street #3, Hudson, NY 12534'
baseurl: 
url: http://septembergallery.com
facebook_username: septembergallery
instagram_username: septembergallery
markdown: kramdown
gems:
- jekyll-sitemap
