---
title: Your awesome title
timezone: America/New_York
collections:
  posts:
    title: Posts
    output: true
  space:
    title: Space
    output: true
  uploads:
    title: Uploads
    output: true
  work:
    title: Work
    output: true
email: jsnhff@gmail.com
description: |
  September Gallery.
baseurl: 
url: http://yourdomain.com
twitter_username: jsnhff
github_username: jsnhff
markdown: kramdown
