source 'https://rubygems.org'
gem 'github-pages'
gem 'jekyll-sitemap'
gem 'redcarpet', '>= 3.5.1'
gem 'kramdown', '>= 2.3.1'
gem 'json', '>= 2.3.0'
gem 'jekyll', '>= 3.6.3'
gem 'ffi', '>= 1.9.24'
gem 'nokogiri', '>= 1.11.0'
